development:
  sessions:
    default:
      database: abandoned_carts_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: abandoned_carts_test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: abandoned_carts_production
      hosts:
        - localhost:27017